### ISSUE TITLE
奇怪的未知原因问题，以非管理员方式运行py文件。运行以后电脑强行关机

### ISSUE THREAD

**Issue by xiezhipeng-git** [erew123/deepspeedpatcher#1]
@erew123 
windows11
使用vscode 打开工程。点击.py文件,以后，电脑强行关机。直接断电的那种

**Comment by erew123** [comment]
代码中没有任何内容会导致这种情况，所以我怀疑是你的电脑或 VS Code 的安装出现了其他问题

There is nothing in the code that would do that, so I suspect you have some other issue with your computer or your installation of VS code

**Comment by xiezhipeng-git** [comment]
我也感到很奇怪。好像是检查是否是管理员的那个弹窗。点了强行断电

**Comment by xiezhipeng-git** [comment]
![image](https://github.com/user-attachments/assets/5e8a3c7b-a9e5-4c11-bf84-7c5ab317b0d8)
用管理员的方式可以打开

**Comment by xiezhipeng-git** [comment]
![image](https://github.com/user-attachments/assets/69c84743-a443-4e63-8b6f-a8fed333ebd5)
ben本地已经有vs2022了，没有检测到

**Comment by erew123** [comment]
请查看官方的 Microsoft DeepSpeed 网站：https://github.com/microsoft/DeepSpeed/blob/9500ab7d476aaf60ec2c76653c67bf5feb758f9e/build_win.bat

DeepSpeed 编译/构建需要管理员权限。因此，我必须请求管理员权限，这是无法绕过的要求。

如果您有疑虑，可以手动构建 DeepSpeed，相关说明请见此链接：https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#manual-builds-of-deepspeed-0150-and-later

此外，您也会看到需要以管理员身份打开命令提示符：https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#manual-build-steps

关于 Visual Studio，我在此列出了所有的前置要求：https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#before-running-the-tool 我无法确认非英文操作系统上的 Visual Studio 是否会被不同地检测到，因为我对 Microsoft 产品和本地化的了解有限。

Please see here, from the official Microsoft DeepSpeed site, https://github.com/microsoft/DeepSpeed/blob/9500ab7d476aaf60ec2c76653c67bf5feb758f9e/build_win.bat

DeepSpeed requires Administrator privilege to build/compile. As such, I have to request administrator rights, there is no way to work around this requirement.

If you are concerned, you can always build DeepSpeed manually, I include the instructions for doing this here https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#manual-builds-of-deepspeed-0150-and-later

You will also see that you have to open Command Prompt as the administrator https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#manual-build-steps

As for Visual Studio, I state all pre-requisites https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#before-running-the-tool I cannot say if Visual Studio on non-english computers may be detected differently. I dont have that amount of knowledge of Microsoft Products and localisation.

**Comment by xiezhipeng-git** [comment]
![image](https://github.com/user-attachments/assets/507c4e42-13ed-4fab-ae82-73e991d3ceda)
@erew123 
能看出少了什么吗？ 没检测到vs

**Comment by xiezhipeng-git** [comment]
@erew123 
vs_paths = {
                "VS2019 BuildTools": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools",
                "VS2019 Community": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
                "VS2022 BuildTools": "C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools",
                "VS2022 Community": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community"
            }
            
路径问题？C D path？

**Comment by erew123** [comment]
很难说，我不懂中文，但看起来是正确的。

这段代码会查找 Visual Studio 是否安装在默认路径中。如果需要，您可以更改这些代码行，以指向正确的路径：https://github.com/erew123/deepspeedpatcher/blob/main/builddeepspeed.py#L601-L606

您需要将版本更改为与您的路径匹配：

python

vs_paths = {
    "VS2019 BuildTools": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2019\\BuildTools",
    "VS2019 Community": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2019\\Community",
    "VS2022 BuildTools": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2022\\BuildTools",
    "VS2022 Community": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2022\\Community"
}

它正在尝试找到 vcvars64.bat，因为这是编译所需的。


Hard to say, I dont understand chinese, but it looks correct.

The code looks for Visual Studio being installed in the default paths. You can change these lines of code if needed to point it to the correct path https://github.com/erew123/deepspeedpatcher/blob/main/builddeepspeed.py#L601-L606

You would change the version to match your path:

vs_paths = {
    "VS2019 BuildTools": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2019\\BuildTools",
    "VS2019 Community": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2019\\Community",
    "VS2022 BuildTools": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2022\\BuildTools",
    "VS2022 Community": "C:\\Your\\Custom\\Path\\To\\Microsoft Visual Studio\\2022\\Community"
}

It is trying to find `vcvars64.bat` as this is needed to compile.

**Comment by xiezhipeng-git** [comment]
vs_paths = {
                "VS2019 BuildTools": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools",
                "VS2019 Community": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
                "VS2022 BuildTools": "D:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools",
                # "VS2022 Community": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
                "VS2022 Community": "D:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
            }
            change path also can not finde vs

**Comment by xiezhipeng-git** [comment]
if only a  bat file.why not copy it to project.then run it?

**Comment by erew123** [comment]
代码应该在所有这些路径中查找，然后将 `VC\\Auxiliary\\Build\\vcvars64.bat` 添加到路径中，以找到 `vcvars64.bat` 文件。

这在以下行中： https://github.com/erew123/deepspeedpatcher/blob/main/builddeepspeed.py#L610

所以请检查您是否在 `D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\` 位置中有 `vcvars64.bat` 文件。

除此之外，我无法判断，这可能是某种本地化问题。

RE: if only a bat file.why not copy it to project.then run it?
我不确定不同版本之间是否存在差异。我没有花时间安装不同版本的 Visual Studio，也没有仔细研究它实际在做什么。我只是写这个来帮助我自己的项目。


The code should look in all those paths, then add `VC\\Auxiliary\\Build\\vcvars64.bat` onto the path to find the `vcvars64.bat` file. 

This is in line:
https://github.com/erew123/deepspeedpatcher/blob/main/builddeepspeed.py#L610

So check you have `vcvars64.bat`  in the `D:\\Program Files\\Microsoft Visual Studio\\2022\\Community`VC\\Auxiliary\\Build\\` location.

Beyond that, I cannot say, it could be a localisation issue of some kind.

**Comment by erew123** [comment]
欢迎您将 bat 文件放在脚本中提到的任意位置，这样应该可以通过检查。不过，我不能确定它是否会运行。

**Comment by xiezhipeng-git** [comment]
have two place path position. chang it found vs

**Comment by xiezhipeng-git** [comment]
@erew123 
There are too more buttons.
I need click build and install?

**Comment by erew123** [comment]
https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#usage-guide

构建选项
仅构建：创建不带安装的轮文件
安装已构建的轮：安装之前构建的轮
构建和安装：执行这两项操作
CUDA_HOME 设置指南：显示 CUDA_HOME 配置说明

Build Options
Build Only: Creates wheel file without installation
Install Built Wheel: Installs previously built wheel
Build and Install: Performs both operations
CUDA_HOME Setup Guide: Shows CUDA_HOME configuration instructions

**Comment by xiezhipeng-git** [comment]
![image](https://github.com/user-attachments/assets/937ee85c-dce2-4da9-a829-986895e1eed1)
Is it download deepspeed source code?can

**Comment by erew123** [comment]
是的，它直接从微软的 GitHub 网站下载 DeepSpeed。如果您无法访问该网站，或者在浏览器的 SSL 证书方面遇到问题，那将是一个问题。

Yes it downloads DeepSpeed directly from Microsoft's Github website. If you are blocked from accessing it, or have issues with your browsers SSL certificates, that would be a problem.

**Comment by xiezhipeng-git** [comment]
a zip .I need put the file in Installation Directory?
