### ISSUE TITLE
Screen height

### ISSUE THREAD

**Issue by DadamaldaDad** [erew123/deepspeedpatcher#2]
This tool has an extra requirement  of screen height.
I had to decrease my display scale to see the buttons.
Please make the window scrollable to make this tool more accessible.

**Comment by erew123** [comment]
@DadamaldaDad 

I dont have spare time to work on this in any major way. Ive managed to scale the buttons larger though.

![image](https://github.com/user-attachments/assets/58a70849-42ab-4d33-bec6-595d8df5478c)
